### ISSUE TITLE
rework create role backend

### ISSUE THREAD

**Issue by Nanciee** [mcgovern-campbell-technologies/tbd#122]
AC:
- Redefine the role node to include: name, trade Id, position level Id, position number, and id
- Refactor related api to take in new shape

**Comment by Luke-Wilson** [comment]
Discuss with @evenkeeler

**Comment by Luke-Wilson** [comment]
@Nanciee This is dependent on the resolution of #131. Let me know your thoughts on that ticket when you get a sec.
